
const navToggle=document.querySelector('[data-nav-toggle]'),navLinks=document.querySelector('[data-nav-links]');
function closeNav(){if(!navLinks||!navToggle)return;navLinks.classList.remove('is-open');navToggle.setAttribute('aria-expanded','false')}
if(navToggle&&navLinks){navToggle.addEventListener('click',()=>{const open=navLinks.classList.toggle('is-open');navToggle.setAttribute('aria-expanded',String(open))});navLinks.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeNav));document.addEventListener('keydown',e=>{if(e.key==='Escape'&&navLinks.classList.contains('is-open')){closeNav();navToggle.focus()}})}
const siteHeader=document.querySelector('.site-header');
if(siteHeader){const onScroll=()=>siteHeader.classList.toggle('is-scrolled',window.scrollY>24);onScroll();window.addEventListener('scroll',onScroll,{passive:true})}
document.querySelectorAll('img').forEach(img=>img.addEventListener('error',()=>{img.hidden=true}));
const revealEls=document.querySelectorAll('.reveal');if('IntersectionObserver'in window){const io=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');io.unobserve(entry.target)}}),{threshold:.12});revealEls.forEach(el=>io.observe(el))}else revealEls.forEach(el=>el.classList.add('is-visible'));
const modal=document.querySelector('[data-video-modal]'),frame=document.querySelector('[data-video-frame]'),close=document.querySelector('[data-close-video]');
function closeModal(){if(!modal)return;modal.classList.remove('is-open');modal.setAttribute('aria-hidden','true');document.body.classList.remove('modal-open');if(frame)frame.innerHTML=''}
document.querySelectorAll('[data-open-video]').forEach(btn=>btn.addEventListener('click',()=>{if(!modal||!frame)return;frame.innerHTML=`<iframe src="${btn.dataset.videoSrc}" title="Alexis King speaker reel" allow="autoplay; fullscreen" allowfullscreen></iframe>`;modal.classList.add('is-open');modal.setAttribute('aria-hidden','false');document.body.classList.add('modal-open');close?.focus()}));close?.addEventListener('click',closeModal);modal?.addEventListener('click',e=>{if(e.target===modal)closeModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
document.querySelectorAll('[data-event-end]').forEach(row=>{const end=new Date(row.dataset.eventEnd+'T23:59:59');if(!Number.isNaN(end.getTime())&&new Date()>end)row.hidden=true});
document.querySelectorAll('form[data-mock-form]').forEach(form=>form.addEventListener('submit',e=>{e.preventDefault();const note=form.querySelector('[data-form-status]');if(note)note.textContent='Prototype only — connect this form to GoHighLevel before launch.'}));
document.querySelectorAll('[data-touch-glow]').forEach(el=>{const on=()=>el.classList.add('is-touch-active'),off=()=>setTimeout(()=>el.classList.remove('is-touch-active'),200);el.addEventListener('touchstart',on,{passive:true});el.addEventListener('touchend',off,{passive:true});el.addEventListener('touchcancel',off,{passive:true})});
document.querySelectorAll('.accordion-trigger').forEach(btn=>btn.addEventListener('click',()=>{const open=btn.getAttribute('aria-expanded')==='true';btn.setAttribute('aria-expanded',String(!open));const panel=document.getElementById(btn.getAttribute('aria-controls'));panel?.classList.toggle('is-open',!open)}));
const keynoteSections=document.querySelectorAll('[data-keynote-section]'),keynoteLinks=document.querySelectorAll('.keynote-select-item');
if(keynoteSections.length&&keynoteLinks.length&&'IntersectionObserver'in window){const linkMap={};keynoteLinks.forEach(a=>{linkMap[a.getAttribute('href').slice(1)]=a});const io3=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){keynoteLinks.forEach(a=>a.classList.remove('is-current'));linkMap[entry.target.id]?.classList.add('is-current')}}),{rootMargin:'-35% 0px -55% 0px'});keynoteSections.forEach(s=>io3.observe(s))}
