
const navToggle=document.querySelector('[data-nav-toggle]'),navLinks=document.querySelector('[data-nav-links]');
if(navToggle&&navLinks){navToggle.addEventListener('click',()=>{const open=navLinks.classList.toggle('is-open');navToggle.setAttribute('aria-expanded',String(open))});navLinks.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{navLinks.classList.remove('is-open');navToggle.setAttribute('aria-expanded','false')}))}
document.querySelectorAll('img').forEach(img=>img.addEventListener('error',()=>{img.hidden=true}));
const revealEls=document.querySelectorAll('.reveal');if('IntersectionObserver'in window){const io=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');io.unobserve(entry.target)}}),{threshold:.12});revealEls.forEach(el=>io.observe(el))}else revealEls.forEach(el=>el.classList.add('is-visible'));
const modal=document.querySelector('[data-video-modal]'),frame=document.querySelector('[data-video-frame]'),close=document.querySelector('[data-close-video]');
function closeModal(){if(!modal)return;modal.classList.remove('is-open');modal.setAttribute('aria-hidden','true');document.body.classList.remove('modal-open');if(frame)frame.innerHTML=''}
document.querySelectorAll('[data-open-video]').forEach(btn=>btn.addEventListener('click',()=>{if(!modal||!frame)return;frame.innerHTML=`<iframe src="${btn.dataset.videoSrc}" title="Alexis King speaker reel" allow="autoplay; fullscreen" allowfullscreen></iframe>`;modal.classList.add('is-open');modal.setAttribute('aria-hidden','false');document.body.classList.add('modal-open');close?.focus()}));close?.addEventListener('click',closeModal);modal?.addEventListener('click',e=>{if(e.target===modal)closeModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
document.querySelectorAll('[data-event-end]').forEach(row=>{const end=new Date(row.dataset.eventEnd+'T23:59:59');if(!Number.isNaN(end.getTime())&&new Date()>end)row.hidden=true});
document.querySelectorAll('form[data-mock-form]').forEach(form=>form.addEventListener('submit',e=>{e.preventDefault();const note=form.querySelector('[data-form-status]');if(note)note.textContent='Prototype only — connect this form to GoHighLevel before launch.'}));
